### ISSUE TITLE
Use with wasi-shim?

### ISSUE THREAD

**Issue by nickwesselman** [jedisct1/as-wasi#127]
I see you've updated to use `wasi-shim`, but it's not clear how usage/configuration has changed.

* No more need to `import "wasi"`, right?
* How do I correctly [configure](https://github.com/AssemblyScript/wasi-shim#usage) my `asconfig.json`?

Adding nothing results in a module that won't execute:
```
Error: failed to run main module `build/debug.wasm`

Caused by:
    0: failed to instantiate "build/debug.wasm"
    1: unknown import: `env::abort` has not been defined
```

Following the [instructions](https://github.com/AssemblyScript/wasi-shim#usage) from `wasi-shim` results in a module that won't compile.
```
ERROR TS2300: Duplicate identifier 'wasi_abort'.
      :
 1100 │ export function wasi_abort(
      │                 ~~~~~~~~~~
      └─ in ~lib/as-wasi/assembly/as-wasi.ts(1100,17)
    :
 19 │ export function wasi_abort(
    │                 ~~~~~~~~~~
    └─ in ~lib/wasi_internal.ts(19,17)
```

**Comment by nickwesselman** [comment]
Note if I comment out the `wasi-abort` global in `assembly/as-wasi.ts` things seem to work great. Is this global no longer needed with the shim?

**Comment by JairusSW** [comment]
I am also having the same problem

**Comment by mariusa** [comment]
Thanks! Would you please make a new release with this fix?

**Comment by mariusa** [comment]
PS: there's an error on build now

```
> asc assembly/index.ts -b build/optimized.wasm -t build/optimized.wat --use abort=wasi_abort -O3

ERROR AS[11](https://github.com/jedisct1/as-wasi/actions/runs/3468757099/jobs/5794936368#step:5:12)1: Element 'wasi_abort' not found.
```

**Comment by dcodeIO** [comment]
I guess ideally, both wasi-shim and as-wasi are used alongside, where wasi-shim reconfigures stdlib to use WASI APIs while as-wasi provides additional APIs that are not present in stdlib. Seems this could work well as the default, given that:
* as-wasi depends on wasi-shim already anyway
* Could then remove redundant APIs like
  * `Console.*` (wasi-shim implements std `console.*`)
  * `Time.*` (wasi-shim implements std `Date.*` and `performance.*`)
  * `Environ.*` (wasi-shim implements node-like `process.*`)
* Whereas as-wasi can focus on additional APIs like file system access

**Comment by mariusa** [comment]
There's no `console.readAll()` -- should I open an issue? 

btw, https://github.com/AssemblyScript/wasi-shim doesn't have issues enbabled

**Comment by dcodeIO** [comment]
wasi-shim only overrides APIs already in AS's stdlib, that is standard-ish JS or, where useful, Node APIs. A `console.readAll` with no equivalent in JS/Node should remain in as-wasi, unless it can be refactored to map to an actual JS/Node API that is first added to AS stdlib, and then overridden by wasi-shim.
