### ISSUE TITLE
Reading/Writing to a file without permissions should error?

### ISSUE THREAD

**Issue by torch2424** [jedisct1/as-wasi#13]
For example in: https://github.com/jedisct1/as-wasi/blob/master/assembly/as-wasi.ts#L281

I didn't realize I had the wrong permissions when opening a file, so when I tried to write to the file, it would silently fail. Perhaps we should think of a way to handle this? 😄

**Comment by jedisct1** [comment]
Hi!

Oh, absolutely. All I/O functions can fail, so returning `void` isn't the right thing to do here :/

**Comment by torch2424** [comment]
@jedisct1 Awesome! I'll try an open a PR once I get the chance so we can make it error or something 😄 👍
