### ISSUE TITLE
Console.readAll blocks until EOF

### ISSUE THREAD

**Issue by mhonert** [jedisct1/as-wasi#20]
The Console.readAll function blocks until the EOF character is entered (e.g. by pressing CTRL-D in a linux shell), so it is not that useful for a CLI application.

It would be great if there was a function which reads a whole line until a newline character is entered (e.g. Console.readLine).

For portability this should probably take different newline character sequences into account (e.g. CR+LF for Windows and only LF for Linux/macOS).

**Comment by jedisct1** [comment]
I'm not sure how to do that. WASI doesn't expose anything about the underlying environment, so we don't know what an end of line looks like.

**Comment by MaxGraey** [comment]
I guess it relate to this discussion: https://github.com/WebAssembly/WASI/issues/162

**Comment by mhonert** [comment]
If we can assume that a newline always ends with LF regardless of the platform, then
a simple solution would perhaps be to skip any CR characters?
At least this is how I implemented it for now in my chess engine, which reads UCI protocol commands from STDIN.

But I do not know, whether there are any use cases where recognizing the CR character might be necessary.

**Comment by mhonert** [comment]
I had a look at the ReadLine implementation of Go and they simply skip the CR (\r) character as well, if it is followed by a LF (\n): [bufio.go](https://github.com/golang/go/blob/master/src/bufio/bufio.go#L412-L417).

**Comment by jedisct1** [comment]
But then, we have a similar problem with the `WriteLine()` counterpart.

**Comment by mhonert** [comment]
It seems that Go always writes '\n', regardless of the platform. For console output this is probably fine, although I did not yet check what happens when stdout is redirected to a file in Windows.
