### ISSUE TITLE
README gives wrong npm install

### ISSUE THREAD

**Issue by MendyBerger** [jedisct1/as-wasi#67]
In the README it says to install by running `npm install --save as-bind` instead of `npm install --save as-wasi`, is this a mistake or am I missing something?

**Comment by MaxGraey** [comment]
No, it's just a tricky plan to promote as-bind by @torch2424 =)

**Comment by MendyBerger** [comment]
Worked for me, I'm now trying out `as-bind` instead of `@assemblyscript/loader`...

**Comment by jedisct1** [comment]
Ahahah, well played, @torch2424 :)

**Comment by jedisct1** [comment]
Fixed.

Good catch, thanks!

**Comment by torch2424** [comment]
Ahhhhhhh! I am so sorry @jedisct1 ! :cry: @MaxGraey I promise it's not a plan to promote `as-bind` (though I am sure you are joking) :joy: I copy-pasted a lot of the structure from the as-bind readme, and re-filled it out, and forgot to change the npm install :upside_down_face: 

Again! My Apologies!

**Comment by MaxGraey** [comment]
Of course I joking!)
