### ISSUE TITLE
Install from Npm?

### ISSUE THREAD

**Issue by torch2424** [jedisct1/as-wasi#7]
Hello!

Was wondering if you were going to allow this to be npm-installable? 😄 

It could be installed from the Github directly if we add a `name` field to the `package.json`.

Thanks! 😄

**Comment by jedisct1** [comment]
`wasa` is already taken on Npm :(

Do you have a suggestion for an alternative name?

**Comment by torch2424** [comment]
You can scope it, like: `@jedisct1/wasa` if you want to keep the name 😄 

That or we can rename it to like `as-wasa` or something like that? 😄
