### ISSUE TITLE
Environment variables whose rvalue contains an `=` gets truncated

### ISSUE THREAD

**Issue by technosophos** [jedisct1/as-wasi#83]
As far as I can tell, it is legal to have an environment variable like this:

```
QUERY_STRING=bar=baz
```

This is equivalent to `QUERY_STRING="bar=baz"`.

However, if I try to access the above in `as-wasi`'s `Envron`, I get only `bar`.

```typescript
import { Console, Environ } from "as-wasi";

let env = new Environ();

// export QUERY_STRING=bar=baz
let foo_env = env.get("QUERY_STRING")
let foo = foo_env === null ? "not set" : <string>foo_env;
Console.log("Value of QUERY_STRING: " + foo);
```

The problem seems to be that `split("=", 2)` splits all of the `=`, but then returns only the first 2 results (unlike similar functions in other languages that actually stop parsing once the limit is reached).

**Comment by technosophos** [comment]
I think @radu-matei might have a patch that he is almost done with.

**Comment by MaxGraey** [comment]
Great!
