### ISSUE TITLE
Program execution is stopped because proc_exit is invoked with a not allowed value

### ISSUE THREAD

**Issue by flavio** [jedisct1/as-wasi#97]
> This is a follow up of https://github.com/jedisct1/as-wasi/issues/95 - the reproducer is always the same, but I'm going to write it.

I've written a simple "echo" program using [AssemblyScript](https://www.assemblyscript.org) and [as-wasi](https://github.com/jedisct1/as-wasi). The program reads the user input from STDIN and writes it back to STDOUT.

Unfortunately the program crashes right after the `EOF` symbol is received.

- What are the steps to reproduce the issue?

This the source code of the AssemblyScript program I'm running:

```ts

import "wasi"

import {Console} from "as-wasi"

Console.log("type something");

let input: string | null;
let msg : string = "nothing";

input = Console.readAll();
if (input != null) {
  msg = input!
}

Console.log('I got: ' + msg);
```

The program can be compiled to a WASM binary by doing:

```shell
$ asc echo.ts -b echo.wasm
```
And it can be run in this way:

```shell
$ wasmtime run echo.wasm
```

The program starts and I can enter my text. The program keeps reading from STDIN until it gets the `EOF` symbol (I'm on Linux -> `CTRL-D`).

The program crashes as soon as the `EOF`, this is the output I get:

```shell
type something
abort:  in ~lib/rt/pure.ts(112:14)
Error: failed to run main module `stdin-test.wasm`

Caused by:
    0: failed to invoke command default
    1: exit with invalid exit status outside of [0..126)
       wasm backtrace:
         0:  0x555 - <unknown>!<wasm function 9>
         1:  0x1f6 - <unknown>!<wasm function 3>
         2:  0x209 - <unknown>!<wasm function 4>
         3: 0x2490 - <unknown>!<wasm function 54>
         4: 0x2584 - <unknown>!<wasm function 57>
         5: 0x25d8 - <unknown>!<wasm function 58>
```
This can be triggered also in an automated fashion:

```shell
$ echo "hello" | wasmtime run echo.wasm
```

- What do you expect to happen? What does actually happen? Does it panic, and
  if so, with which assertion?

I would expect the WASM program to be able to read data from stdin. The `input` object should hold the text I entered on my terminal.

- Which Wasmtime version / commit hash / branch are you using?

This is my stack:

  * wasmtime: 0.21.0
  * AssemblyScript: 0.17.3
  * `as-wasi`: 0.4.3

- If relevant, can you include some extra information about your environment?
  (Rust version, operating system, architecture...)

I'm running on a x86_64 Linux box that has openSUSE Tumblewee

According to [this comment](https://github.com/jedisct1/as-wasi/issues/95#issuecomment-730687828) from @peterhuene:

> It looks like something is calling `proc_exit` with an exit code outside of the WASI-defined acceptable range of [0..126) (granted this range isn't part of the current WASI snapshot yet, so Wasmtime is being a little overzealous with this enforcement).

**Comment by MaxGraey** [comment]
> 1: exit with invalid exit status outside of [0..126)

Hmm, `wasi_abort` uses `255` code: 
https://github.com/jedisct1/as-wasi/blob/master/assembly/as-wasi.ts#L1105

**Comment by jedisct1** [comment]
Ah, good catch!

**Comment by jedisct1** [comment]
The standard `abort()` call returns `134` though (probably on all POSIX systems).

**Comment by MaxGraey** [comment]
Will be great create status code `enum` which contain all possible status codes btw)

**Comment by jedisct1** [comment]
And the WASI libc just traps.

What should we do here?

**Comment by MaxGraey** [comment]
what is error?

Btw basic example in README probably should update as:
```ts
import "wasi" // <----- new

// Import from the installed as-wasi package
import { Console, Environ } from "as-wasi";

// Create an envrion instance
let env = new Environ();

// Get the HOME Environment variable
let home = env.get("HOME")!;

// Log the HOME string to stdout
Console.log(home);
```

**Comment by peterhuene** [comment]
See [this issue](https://github.com/WebAssembly/WASI/pull/235) as to why WASI might eventually limit the range for `proc_exit`.  Wasmtime simply restricted the range a little early in anticipation of this PR making its way into a future WASI snapshot.

I can bug Dan as to whether or not we should abandon the WASI PR and revert the restriction in Wasmtime or merge the PR and continue to enforce the valid range in Wasmtime.

**Comment by jedisct1** [comment]
In `wasi-libc`, `abort()` just calls `__trap()` which looks quite reasonable. An exit code > 127 will also trap, so we get a consistent behavior?

**Comment by jedisct1** [comment]
In Zig, we return `1` on panic.

Well... maybe the best thing to do `as-wasi` would be to return `1` as well, then, at least for now.

**Comment by flavio** [comment]
@jedisct1 thanks, I can confirm `as-wasi` version `0.4.4` is **not** affected by this issue. Everything is working as expected :smiley:
