### ISSUE TITLE
readLine doesn't return null when the end of the file is reached

### ISSUE THREAD

**Issue by ColinEberhardt** [jedisct1/as-wasi#98]
The following reads a file line, by line, with the assumption that `readLine` returns `null` at the end of file:

index.ts:

```
import "wasi";

import { Console, FileSystem, Descriptor } from "as-wasi";

const filePath: string = "data.txt";
const fileOrNull: Descriptor | null = FileSystem.open(filePath, "r");
if (fileOrNull == null) {
  throw new Error("Could not open the file " + filePath);
}
const file = changetype<Descriptor>(fileOrNull);

let line = changetype<string>(file.readLine());
while (line) {
  Console.log(line);
  line = changetype<string>(file.readLine());
}
```

package.json:

```
{
  "scripts": {
    "build": "asc assembly/index.ts -b build/index.wasm -t build/index.wat --runtime half",
    "start": "wasmtime --dir . build/index.wasm",
    "build:run": "npm run build && npm start"
  },
  "devDependencies": {
    "assemblyscript": "0.17.3"
  },
  "dependencies": {
    "as-wasi": "0.4.4"
  }
}
```

However, `readLine` never returns null. 

I instead have to check for an empty line:

```
xlet line = changetype<string>(file.readLine());
while (line.length > 0) {
  Console.log(line);
  line = changetype<string>(file.readLine());
}
```

**Comment by jedisct1** [comment]
A `null` return value was supposed mean that an error occurred. The end of a file is not an error.

However, since this is apparently confusing, the behavior has been changed. `null` is now also returned when the whole file has been successfully read.

**Comment by ColinEberhardt** [comment]
Nice one - thanks @jedisct1

**Comment by pmuens** [comment]
Thanks for resolving this!

FYI: Not checking for the line length will result in an "memory access out of bounds" error. Adding this comment to make it easier to discover via Googling (as I ran into this memory error and couldn't figure out why it happened).
